{% set name = "grpcio-tools" %}
{% set version = "1.48.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grpcio-tools-{{ version }}.tar.gz
  sha256: 8902a035708555cddbd61b5467cea127484362decc52de03f061a1a520fe90cd

build:
#  skip: true  # [py<37]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.7
    - cython
    - pip
  run:
    - python >=3.7
    - protobuf >=3.12.0,<4.0dev
    - grpcio >=1.48.2
    - setuptools

test:
  imports:
    - grpc_tools
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://grpc.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Protobuf code generator for gRPC
  doc_source_url: https://github.com/grpc/grpc/tree/master/doc
  doc_url: https://grpc.io/docs/
  dev_url: https://github.com/grpc/grpc/tree/master/tools

extra:
  recipe-maintainers:
    - martinRenou
    - janjagusch
